# Generated by Django 5.1.3 on 2024-11-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('quantidade_estoque', models.PositiveIntegerField()),
                ('fornecedor', models.CharField(max_length=255)),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('unidade_medida', models.CharField(default='unidade', max_length=50)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('esgotado', 'Esgotado')], default='ativo', max_length=20)),
            ],
        ),
    ]
